// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:crux_cxp/crux_cxp.dart';
import 'package:meta/meta.dart';
import 'package:netcrux/domain/models/fsm/fsm_encoding_hint.dart';
import 'package:netcrux/domain/models/fsm/fsm_state.dart';
import 'package:netcrux/domain/models/fsm/fsm_transition.dart';

/// A finite state machine detected in the netlist.
///
/// Holds the structural recovery of the FSM: which register encodes the
/// state, which module instance contains it, the set of states the
/// detector classified, the transitions between them, and the inferred
/// encoding hint. The bubble diagram panel renders this directly.
///
/// Distinct from WaveCrux's `FsmModel`, which is recovered from a
/// signal's runtime value changes. NetCrux's `Fsm` is recovered from
/// the netlist graph — it describes the FSM's *structure* before any
/// simulation runs.
@immutable
class Fsm {
  /// Creates an FSM record.
  const Fsm({
    required this.id,
    required this.stateRegisterId,
    required this.stateRegisterName,
    required this.containingInstanceId,
    required this.states,
    required this.transitions,
    required this.encodingHint,
    this.resetStateId,
  });

  /// JSON round-trip constructor.
  factory Fsm.fromJson(Map<String, Object?> json) {
    final stateRegisterRaw = json['stateRegisterId'];
    final containingInstanceRaw = json['containingInstanceId'];
    final encodingStr =
        json['encodingHint']?.toString() ?? FsmEncodingHint.unknown.name;
    final statesRaw = json['states'];
    final transitionsRaw = json['transitions'];
    return Fsm(
      id: json['id']?.toString() ?? '',
      stateRegisterId: stateRegisterRaw is Map<String, Object?>
          ? ElementId.fromJson(stateRegisterRaw)
          : const ElementId(kind: ElementKind.signal, path: ''),
      stateRegisterName: json['stateRegisterName']?.toString() ?? '',
      containingInstanceId: containingInstanceRaw is Map<String, Object?>
          ? ElementId.fromJson(containingInstanceRaw)
          : const ElementId(kind: ElementKind.instance, path: ''),
      states: statesRaw is List
          ? <FsmState>[
              for (final s in statesRaw)
                if (s is Map<String, Object?>) FsmState.fromJson(s),
            ]
          : const <FsmState>[],
      transitions: transitionsRaw is List
          ? <FsmTransition>[
              for (final t in transitionsRaw)
                if (t is Map<String, Object?>) FsmTransition.fromJson(t),
            ]
          : const <FsmTransition>[],
      encodingHint: FsmEncodingHint.values.firstWhere(
        (e) => e.name == encodingStr,
        orElse: () => FsmEncodingHint.unknown,
      ),
      resetStateId: json['resetStateId']?.toString(),
    );
  }

  /// Stable identifier (UUID-shaped string) generated by the detector.
  /// Keys the FSM in the detection result and survives re-detection so
  /// the bubble diagram can preserve user-arranged bubble positions
  /// across refreshes.
  final String id;

  /// Canonical cross-suite identifier for the register whose value
  /// enumerates this FSM's states. Built via the resolver so it
  /// interoperates with the rest of the per-tab schematic-selection
  /// surfaces (cross-probe, source pane, bookmarks).
  final ElementId stateRegisterId;

  /// Human-readable name of the state register, for display in the
  /// panel header and detection-results dialog (e.g. `"state_q"`).
  final String stateRegisterName;

  /// Cross-suite identifier for the module instance that contains the
  /// FSM. Used by the bubble diagram's header breadcrumb and by the
  /// schematic context menu's "Detect FSM" entry to scope detection
  /// reruns.
  final ElementId containingInstanceId;

  /// All detected states, in detector-discovery order. `FsmState.id`
  /// is the stable handle; `FsmState.value` is the runtime register
  /// value.
  final List<FsmState> states;

  /// All detected transitions. May include self-loops (per
  /// [FsmTransition.isSelfLoop]).
  final List<FsmTransition> transitions;

  /// Best-guess encoding scheme the detector inferred from the state
  /// values plus the next-state logic. The panel chrome renders this
  /// as a small badge so the user can sanity-check the synthesis
  /// tooling's emitted encoding.
  final FsmEncodingHint encodingHint;

  /// `FsmState.id` of the state the register takes on reset, or null
  /// when the detector could not isolate a single reset state (no
  /// explicit reset, multiple resets, or unparseable reset logic).
  /// The bubble diagram outlines this state in green when present.
  final String? resetStateId;

  /// Convenience lookup by [FsmState.id]. Returns null when no state
  /// in [states] matches.
  FsmState? stateById(String id) {
    for (final s in states) {
      if (s.id == id) return s;
    }
    return null;
  }

  /// JSON map suitable for fixture round-trip.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'stateRegisterId': stateRegisterId.toJson(),
    'stateRegisterName': stateRegisterName,
    'containingInstanceId': containingInstanceId.toJson(),
    'states': <Map<String, Object?>>[
      for (final s in states) s.toJson(),
    ],
    'transitions': <Map<String, Object?>>[
      for (final t in transitions) t.toJson(),
    ],
    'encodingHint': encodingHint.name,
    if (resetStateId != null) 'resetStateId': resetStateId,
  };

  /// Returns a copy with the given fields replaced.
  Fsm copyWith({
    String? id,
    ElementId? stateRegisterId,
    String? stateRegisterName,
    ElementId? containingInstanceId,
    List<FsmState>? states,
    List<FsmTransition>? transitions,
    FsmEncodingHint? encodingHint,
    String? resetStateId,
    bool clearResetStateId = false,
  }) => Fsm(
    id: id ?? this.id,
    stateRegisterId: stateRegisterId ?? this.stateRegisterId,
    stateRegisterName: stateRegisterName ?? this.stateRegisterName,
    containingInstanceId: containingInstanceId ?? this.containingInstanceId,
    states: states ?? this.states,
    transitions: transitions ?? this.transitions,
    encodingHint: encodingHint ?? this.encodingHint,
    resetStateId: clearResetStateId
        ? null
        : (resetStateId ?? this.resetStateId),
  );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Fsm) return false;
    if (runtimeType != other.runtimeType) return false;
    if (id != other.id) return false;
    if (stateRegisterId != other.stateRegisterId) return false;
    if (stateRegisterName != other.stateRegisterName) return false;
    if (containingInstanceId != other.containingInstanceId) return false;
    if (encodingHint != other.encodingHint) return false;
    if (resetStateId != other.resetStateId) return false;
    if (states.length != other.states.length) return false;
    for (var i = 0; i < states.length; i++) {
      if (states[i] != other.states[i]) return false;
    }
    if (transitions.length != other.transitions.length) return false;
    for (var i = 0; i < transitions.length; i++) {
      if (transitions[i] != other.transitions[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    id,
    stateRegisterId,
    stateRegisterName,
    containingInstanceId,
    encodingHint,
    resetStateId,
    Object.hashAll(states),
    Object.hashAll(transitions),
  );

  @override
  String toString() =>
      'Fsm(id: $id, reg: $stateRegisterName, '
      '${states.length} states, ${transitions.length} transitions, '
      'encoding: ${encodingHint.name})';
}
