// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:crux_cxp/crux_cxp.dart';
import 'package:meta/meta.dart';
import 'package:netcrux/domain/models/reset_domain/reset_polarity.dart';
import 'package:netcrux/domain/models/reset_domain/reset_source_kind.dart';
import 'package:netcrux/domain/models/reset_domain/reset_synchronicity.dart';

/// A reset domain detected in the netlist.
///
/// A reset domain is the equivalence class of registers sharing the
/// same effective reset signal — `rst`, the output of a PoR cell, an
/// async-low reset from a primary input, etc. Domain identity is keyed
/// by the *driver net* of the reset signal, not by name, so two
/// registers wired to the same net belong to the same domain even
/// when their HDL refers to the net by different aliases.
///
/// Distinct from a [ClockDomain]: reset domains are scoped by what a
/// reset *resets* (which registers' `.rst` / `.preset` / `.clear`
/// ports does it drive), not by what's downstream in the data path.
/// A single clock domain may host multiple reset domains; a single
/// reset domain may span multiple clock domains.
@immutable
class ResetDomain {
  /// Creates a reset domain record.
  const ResetDomain({
    required this.id,
    required this.resetSignalId,
    required this.resetSignalName,
    required this.polarity,
    required this.synchronicity,
    required this.sourceKind,
    required this.memberRegisters,
    required this.memberNets,
  });

  /// JSON round-trip constructor.
  factory ResetDomain.fromJson(Map<String, Object?> json) {
    final resetRaw = json['resetSignalId'];
    final nets = json['memberNets'];
    final regs = json['memberRegisters'];
    return ResetDomain(
      id: json['id']?.toString() ?? '',
      resetSignalId: resetRaw is Map<String, Object?>
          ? ElementId.fromJson(resetRaw)
          : const ElementId(kind: ElementKind.signal, path: ''),
      resetSignalName: json['resetSignalName']?.toString() ?? '',
      polarity: ResetPolarity.fromJsonString(
        json['polarity']?.toString() ?? '',
      ),
      synchronicity: ResetSynchronicity.fromJsonString(
        json['synchronicity']?.toString() ?? '',
      ),
      sourceKind: ResetSourceKind.fromJsonString(
        json['sourceKind']?.toString() ?? '',
      ),
      memberRegisters: regs is List
          ? <ElementId>[
              for (final r in regs)
                if (r is Map<String, Object?>) ElementId.fromJson(r),
            ]
          : const <ElementId>[],
      memberNets: nets is List
          ? <ElementId>[
              for (final n in nets)
                if (n is Map<String, Object?>) ElementId.fromJson(n),
            ]
          : const <ElementId>[],
    );
  }

  /// Stable identifier (UUID-shaped string) generated by the detector.
  /// Keys the domain in the analysis result; survives re-analysis when
  /// the underlying reset net is unchanged so panels keep their
  /// selection.
  final String id;

  /// Canonical cross-suite identifier for the net that defines this
  /// reset domain. Always present even when the reset arrives through
  /// glue logic — the detector chooses the final net feeding register
  /// reset ports as the domain's identity.
  final ElementId resetSignalId;

  /// Human-readable name of the reset signal (e.g. `"rst_n"`,
  /// `"por_reset"`). Used by panel headers and grouped-list labels.
  final String resetSignalName;

  /// Polarity of the reset — active high, active low, or unknown.
  /// See [ResetPolarity].
  final ResetPolarity polarity;

  /// IEEE 1850 SAS synchronicity classification — see
  /// [ResetSynchronicity]. The headline correctness signal of the
  /// reset domain visualization feature.
  final ResetSynchronicity synchronicity;

  /// How this reset was sourced. See [ResetSourceKind].
  final ResetSourceKind sourceKind;

  /// Cross-suite identifiers of register cells whose reset port is
  /// driven by this domain. The analyzer uses this set to determine
  /// "reset domain of origin" for every register in the design.
  final List<ElementId> memberRegisters;

  /// Cross-suite identifiers of nets that are members of this reset
  /// domain (typically the reset signal itself plus any buffered /
  /// inverted derivatives that still represent the same reset).
  final List<ElementId> memberNets;

  /// Returns a copy with the given fields replaced.
  ResetDomain copyWith({
    String? id,
    ElementId? resetSignalId,
    String? resetSignalName,
    ResetPolarity? polarity,
    ResetSynchronicity? synchronicity,
    ResetSourceKind? sourceKind,
    List<ElementId>? memberRegisters,
    List<ElementId>? memberNets,
  }) => ResetDomain(
    id: id ?? this.id,
    resetSignalId: resetSignalId ?? this.resetSignalId,
    resetSignalName: resetSignalName ?? this.resetSignalName,
    polarity: polarity ?? this.polarity,
    synchronicity: synchronicity ?? this.synchronicity,
    sourceKind: sourceKind ?? this.sourceKind,
    memberRegisters: memberRegisters ?? this.memberRegisters,
    memberNets: memberNets ?? this.memberNets,
  );

  /// JSON map suitable for fixture round-trip.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'resetSignalId': resetSignalId.toJson(),
    'resetSignalName': resetSignalName,
    'polarity': polarity.toJsonString(),
    'synchronicity': synchronicity.toJsonString(),
    'sourceKind': sourceKind.toJsonString(),
    'memberRegisters': <Map<String, Object?>>[
      for (final r in memberRegisters) r.toJson(),
    ],
    'memberNets': <Map<String, Object?>>[
      for (final n in memberNets) n.toJson(),
    ],
  };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! ResetDomain) return false;
    if (id != other.id) return false;
    if (resetSignalId != other.resetSignalId) return false;
    if (resetSignalName != other.resetSignalName) return false;
    if (polarity != other.polarity) return false;
    if (synchronicity != other.synchronicity) return false;
    if (sourceKind != other.sourceKind) return false;
    if (memberRegisters.length != other.memberRegisters.length) return false;
    for (var i = 0; i < memberRegisters.length; i++) {
      if (memberRegisters[i] != other.memberRegisters[i]) return false;
    }
    if (memberNets.length != other.memberNets.length) return false;
    for (var i = 0; i < memberNets.length; i++) {
      if (memberNets[i] != other.memberNets[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    id,
    resetSignalId,
    resetSignalName,
    polarity,
    synchronicity,
    sourceKind,
    Object.hashAll(memberRegisters),
    Object.hashAll(memberNets),
  );

  @override
  String toString() =>
      'ResetDomain(id: $id, name: $resetSignalName, '
      'polarity: ${polarity.name}, '
      'synchronicity: ${synchronicity.name}, '
      'sourceKind: ${sourceKind.name}, '
      '${memberRegisters.length} regs, ${memberNets.length} nets)';
}
