// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:crux_cxp/crux_cxp.dart';
import 'package:meta/meta.dart';
import 'package:netcrux/domain/models/reset_domain/reset_crossing_kind.dart';
import 'package:netcrux/domain/models/reset_domain/reset_polarity.dart';
import 'package:netcrux/domain/models/reset_domain/reset_severity.dart';
import 'package:netcrux/domain/models/reset_domain/reset_synchronizer_status.dart';

/// A signal crossing from one reset domain to another.
///
/// Identified by the analyzer when a register reset by domain A drives
/// a register reset by domain B (A ≠ B), or when a reset signal from
/// domain A reaches registers in domain B. The analyzer classifies
/// each crossing along three axes — its [crossingKind] (what is
/// crossing), its [synchronizerStatus] (how it was synchronized), and
/// the source-domain [polarity] (which influences glitch-prone status
/// for opposite-polarity reset crossings) — and derives a [severity]
/// from the deterministic matrix in [severityFor].
@immutable
class ResetCrossing {
  /// Creates a reset crossing record.
  const ResetCrossing({
    required this.id,
    required this.sourceDomainId,
    required this.destinationDomainId,
    required this.signalId,
    required this.signalName,
    required this.crossingKind,
    required this.synchronizerStatus,
    required this.severity,
    required this.confidence,
    required this.sourcePolarity,
    this.synchronizerInstances = const <ElementId>[],
  });

  /// JSON round-trip constructor.
  factory ResetCrossing.fromJson(Map<String, Object?> json) {
    final sigRaw = json['signalId'];
    final instances = json['synchronizerInstances'];
    return ResetCrossing(
      id: json['id']?.toString() ?? '',
      sourceDomainId: json['sourceDomainId']?.toString() ?? '',
      destinationDomainId: json['destinationDomainId']?.toString() ?? '',
      signalId: sigRaw is Map<String, Object?>
          ? ElementId.fromJson(sigRaw)
          : const ElementId(kind: ElementKind.signal, path: ''),
      signalName: json['signalName']?.toString() ?? '',
      crossingKind: ResetCrossingKind.fromJsonString(
        json['crossingKind']?.toString() ?? '',
      ),
      synchronizerStatus: ResetSynchronizerStatus.fromJsonString(
        json['synchronizerStatus']?.toString() ?? '',
      ),
      severity: ResetSeverity.fromJsonString(
        json['severity']?.toString() ?? '',
      ),
      confidence: ResetConfidence.fromJsonString(
        json['confidence']?.toString() ?? '',
      ),
      sourcePolarity: ResetPolarity.fromJsonString(
        json['sourcePolarity']?.toString() ?? '',
      ),
      synchronizerInstances: instances is List
          ? <ElementId>[
              for (final i in instances)
                if (i is Map<String, Object?>) ElementId.fromJson(i),
            ]
          : const <ElementId>[],
    );
  }

  /// Stable identifier (UUID-shaped string) generated by the
  /// analyzer.
  final String id;

  /// `ResetDomain.id` of the domain driving this crossing's signal.
  final String sourceDomainId;

  /// `ResetDomain.id` of the domain consuming this crossing's signal.
  final String destinationDomainId;

  /// Cross-suite identifier for the net that crosses domains. The
  /// schematic overlay highlights this net during selection.
  final ElementId signalId;

  /// Human-readable name of the crossing signal (for panel display).
  final String signalName;

  /// What kind of signal is crossing — data across a reset boundary,
  /// or a reset deassert edge.
  final ResetCrossingKind crossingKind;

  /// How the crossing is synchronized — proper async-assert +
  /// sync-deassert, missing, etc.
  final ResetSynchronizerStatus synchronizerStatus;

  /// Severity derived from
  /// `(crossingKind × synchronizerStatus × polarity)`. See
  /// [severityFor] for the full matrix.
  final ResetSeverity severity;

  /// Detector's confidence in this classification.
  final ResetConfidence confidence;

  /// Polarity of the source reset domain at the time of crossing.
  /// Influences glitch-prone classification for opposite-polarity
  /// reset crossings (active-high source resetting an active-low
  /// destination's logic etc.).
  final ResetPolarity sourcePolarity;

  /// Cross-suite identifiers of the instances forming the
  /// synchronizer chain (or vendor synchronizer cell), in
  /// source-to-destination order.
  final List<ElementId> synchronizerInstances;

  /// Deterministic severity derivation from the
  /// `(crossingKind × synchronizerStatus × polarity)` matrix.
  ///
  /// **Matrix** (rows = crossingKind, columns = synchronizerStatus):
  ///
  /// ```text
  ///                              | properA | properS | properR | custom | glitch | missing |
  /// dataCrossesResetBoundary     | info    | info    | info    | info   | warn   | crit/warn* |
  /// resetDeassertCrossing        | info    | info    | info    | info   | warn   | crit    |
  /// ```
  ///
  /// `*` for `dataCrossesResetBoundary + missingSynchronizer`:
  /// critical at high confidence, warning at medium/low confidence —
  /// the detector's structural certainty matters here because data
  /// paths have more diverse safe patterns than reset paths.
  ///
  /// Rationale:
  ///   * Missing synchronizer on a reset deassert crossing is always
  ///     critical — metastability can propagate to every register in
  ///     the destination domain.
  ///   * Missing synchronizer on a data crossing is critical when the
  ///     detector is certain (a register-driven data net consumed by
  ///     a register in another reset domain) but warning at lower
  ///     confidence to avoid false-positive noise.
  ///   * `glitchProne` is always warning — the synchronizer is
  ///     structurally present but the deassert edge may not be
  ///     cleanly rising.
  ///   * Any kind + a proper synchronizer (async-assert +
  ///     sync-deassert, sync/sync, vendor reset synchronizer, custom)
  ///     is info — the synchronizer is doing its job.
  static ResetSeverity severityFor(
    ResetCrossingKind kind,
    ResetSynchronizerStatus status,
    ResetPolarity polarity, {
    ResetConfidence confidence = ResetConfidence.high,
  }) {
    switch (status) {
      case ResetSynchronizerStatus.properAsyncAssertSyncDeassert:
      case ResetSynchronizerStatus.properSyncAssertSyncDeassert:
      case ResetSynchronizerStatus.properResetSynchronizer:
      case ResetSynchronizerStatus.customSynchronizer:
        return ResetSeverity.info;
      case ResetSynchronizerStatus.glitchProne:
        return ResetSeverity.warning;
      case ResetSynchronizerStatus.missingSynchronizer:
        switch (kind) {
          case ResetCrossingKind.resetDeassertCrossing:
            return ResetSeverity.critical;
          case ResetCrossingKind.dataCrossesResetBoundary:
            return confidence == ResetConfidence.high
                ? ResetSeverity.critical
                : ResetSeverity.warning;
        }
    }
  }

  /// Returns a copy with the given fields replaced.
  ResetCrossing copyWith({
    String? id,
    String? sourceDomainId,
    String? destinationDomainId,
    ElementId? signalId,
    String? signalName,
    ResetCrossingKind? crossingKind,
    ResetSynchronizerStatus? synchronizerStatus,
    ResetSeverity? severity,
    ResetConfidence? confidence,
    ResetPolarity? sourcePolarity,
    List<ElementId>? synchronizerInstances,
  }) => ResetCrossing(
    id: id ?? this.id,
    sourceDomainId: sourceDomainId ?? this.sourceDomainId,
    destinationDomainId: destinationDomainId ?? this.destinationDomainId,
    signalId: signalId ?? this.signalId,
    signalName: signalName ?? this.signalName,
    crossingKind: crossingKind ?? this.crossingKind,
    synchronizerStatus: synchronizerStatus ?? this.synchronizerStatus,
    severity: severity ?? this.severity,
    confidence: confidence ?? this.confidence,
    sourcePolarity: sourcePolarity ?? this.sourcePolarity,
    synchronizerInstances: synchronizerInstances ?? this.synchronizerInstances,
  );

  /// JSON map suitable for fixture round-trip.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'sourceDomainId': sourceDomainId,
    'destinationDomainId': destinationDomainId,
    'signalId': signalId.toJson(),
    'signalName': signalName,
    'crossingKind': crossingKind.toJsonString(),
    'synchronizerStatus': synchronizerStatus.toJsonString(),
    'severity': severity.toJsonString(),
    'confidence': confidence.toJsonString(),
    'sourcePolarity': sourcePolarity.toJsonString(),
    'synchronizerInstances': <Map<String, Object?>>[
      for (final i in synchronizerInstances) i.toJson(),
    ],
  };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! ResetCrossing) return false;
    if (id != other.id) return false;
    if (sourceDomainId != other.sourceDomainId) return false;
    if (destinationDomainId != other.destinationDomainId) return false;
    if (signalId != other.signalId) return false;
    if (signalName != other.signalName) return false;
    if (crossingKind != other.crossingKind) return false;
    if (synchronizerStatus != other.synchronizerStatus) return false;
    if (severity != other.severity) return false;
    if (confidence != other.confidence) return false;
    if (sourcePolarity != other.sourcePolarity) return false;
    if (synchronizerInstances.length != other.synchronizerInstances.length) {
      return false;
    }
    for (var i = 0; i < synchronizerInstances.length; i++) {
      if (synchronizerInstances[i] != other.synchronizerInstances[i]) {
        return false;
      }
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    id,
    sourceDomainId,
    destinationDomainId,
    signalId,
    signalName,
    crossingKind,
    synchronizerStatus,
    severity,
    confidence,
    sourcePolarity,
    Object.hashAll(synchronizerInstances),
  );

  @override
  String toString() =>
      'ResetCrossing(id: $id, $signalName, '
      '$sourceDomainId→$destinationDomainId, '
      'kind: ${crossingKind.name}, status: ${synchronizerStatus.name}, '
      'severity: ${severity.name}, confidence: ${confidence.name}, '
      'polarity: ${sourcePolarity.name})';
}
