// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// integration_test/design/seeded_design_journey_test.dart
//
// Verification driver for the seeded-design journey (Open-Core Guide §4.2):
// load a design (Yosys-free, via the design-seed helper) → navigate the
// hierarchy tree → select an element → inspect it.
//
// The design comes from the committed hierarchical fixture
// (`integration_test/fixtures/design_seed_netlist.dart`, generated by
// `tool/generate_design_seed_fixture.dart`) parsed through the real
// `YosysJsonParser` and injected into the active tab's per-tab
// `loadedNetlistProvider` — the elaboration pipeline itself is pinned
// unavailable so the run is hermetic on hosts without Yosys.

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:netcrux/domain/models/selection/selected_element.dart';
import 'package:netcrux/features/hierarchy/providers/hierarchy_tree_notifier.dart';
import 'package:netcrux/features/hierarchy/widgets/hierarchy_tree_panel.dart';
import 'package:netcrux/features/inspector/widgets/inspector_panel.dart';
import 'package:netcrux/features/project/providers/current_laid_out_graph_provider.dart';
import 'package:netcrux/features/viewer/providers/selected_element_notifier.dart';

import '../fixtures/design_seed_netlist.dart';
import '../helpers/app_driver.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  suppressPlatformSemanticsLeak();

  testWidgets(
    'seeded design: load → navigate hierarchy → select → inspect',
    (tester) async {
      await bootNetcrux(tester, extraOverrides: designSeedBootOverrides());

      final seeded = await seedDesignIntoNewTab(
        tester,
        netlistJson: designSeedNetlistJson,
      );
      final tab = seeded.tab;

      // ── Load: the top scope lays out and the hierarchy shows the root.
      bool graphHasCell(String id) {
        final graph = tab.read(currentLaidOutGraphProvider).value;
        if (graph == null) return false;
        return graph.graph.cells.any((c) => c.id == id);
      }

      final topLaidOut = await pumpUntil(
        tester,
        () => graphHasCell('u_cpu'),
        timeout: const Duration(seconds: 30),
      );
      expect(
        topLaidOut,
        isTrue,
        reason:
            'top scope never laid out (expected cell u_cpu); provider state: '
            '${tab.read(currentLaidOutGraphProvider)}',
      );
      expect(graphHasCell('dma_reg'), isTrue);
      final hierarchyRoot = find.descendant(
        of: find.byType(HierarchyTreePanel),
        matching: find.text('top'),
      );
      expect(hierarchyRoot, findsOneWidget);

      // ── Select in the top scope → inspector renders the cell card.
      tab
          .read(selectedElementProvider.notifier)
          .select(const SelectedElement.cell(cellId: 'u_cpu'));
      expect(
        await pumpUntil(
          tester,
          () => tester.any(
            find.descendant(
              of: find.byType(InspectorPanel),
              matching: find.text('u_cpu'),
            ),
          ),
        ),
        isTrue,
        reason: 'inspector never rendered the selected cell instance',
      );
      expect(
        find.descendant(
          of: find.byType(InspectorPanel),
          matching: find.text('cpu'),
        ),
        findsOneWidget,
        reason: 'inspector cell card shows the module type',
      );

      // ── Navigate: tap the u_cpu hierarchy row. The row label is
      // "u_cpu <module label>", so match on the prefix.
      final cpuRow = find.descendant(
        of: find.byType(HierarchyTreePanel),
        matching: find.textContaining('u_cpu'),
      );
      expect(cpuRow, findsOneWidget);
      await tester.tap(cpuRow);
      final cpuLaidOut = await pumpUntil(
        tester,
        () => graphHasCell('u_alu'),
        timeout: const Duration(seconds: 30),
      );
      expect(
        cpuLaidOut,
        isTrue,
        reason:
            'cpu scope never laid out after hierarchy navigation; '
            'selected=${tab.read(hierarchyTreeProvider).selected} '
            'graph=${tab.read(currentLaidOutGraphProvider)}',
      );
      // HierarchyNode.path is the instance path below the top module.
      expect(
        tab.read(hierarchyTreeProvider).selected?.path,
        <String>['u_cpu'],
      );

      // ── Select inside the navigated scope → inspect the ALU instance.
      tab
          .read(selectedElementProvider.notifier)
          .select(const SelectedElement.cell(cellId: 'u_alu'));
      expect(
        await pumpUntil(
          tester,
          () => tester.any(
            find.descendant(
              of: find.byType(InspectorPanel),
              matching: find.text('u_alu'),
            ),
          ),
        ),
        isTrue,
        reason: 'inspector never rendered the ALU selection',
      );
      expect(
        find.descendant(
          of: find.byType(InspectorPanel),
          matching: find.text('alu'),
        ),
        findsOneWidget,
      );

      // Drain any trailing async work (layout isolates, animations) inside
      // the test body so teardown sees a settled tree.
      for (var i = 0; i < 10; i++) {
        await tester.pump(const Duration(milliseconds: 100));
      }
      tester.takeException();
    },
  );
}
