// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:crux_cxp/crux_cxp.dart';
import 'package:meta/meta.dart';
import 'package:netcrux/domain/models/cdc/cdc_crossing_kind.dart';
import 'package:netcrux/domain/models/cdc/cdc_severity.dart';
import 'package:netcrux/domain/models/cdc/cdc_synchronizer_status.dart';

/// A signal crossing from one clock domain to another.
///
/// Identified by the detector when a net's driver is clocked by domain
/// A and any of its consumers is clocked by domain B (A ≠ B). The
/// detector then classifies the crossing along two axes — its [kind]
/// (signal shape / protocol intent) and its [synchronizerStatus]
/// (whether and how it's been synchronized) — and derives a
/// [severity] from the deterministic matrix in [severityFor].
@immutable
class CdcCrossing {
  /// Creates a CDC crossing record.
  const CdcCrossing({
    required this.id,
    required this.sourceDomainId,
    required this.destinationDomainId,
    required this.signalId,
    required this.signalName,
    required this.crossingKind,
    required this.synchronizerStatus,
    required this.severity,
    required this.confidence,
    this.synchronizerInstances = const <ElementId>[],
  });

  /// JSON round-trip constructor.
  factory CdcCrossing.fromJson(Map<String, Object?> json) {
    final sigRaw = json['signalId'];
    final instances = json['synchronizerInstances'];
    return CdcCrossing(
      id: json['id']?.toString() ?? '',
      sourceDomainId: json['sourceDomainId']?.toString() ?? '',
      destinationDomainId: json['destinationDomainId']?.toString() ?? '',
      signalId: sigRaw is Map<String, Object?>
          ? ElementId.fromJson(sigRaw)
          : const ElementId(kind: ElementKind.signal, path: ''),
      signalName: json['signalName']?.toString() ?? '',
      crossingKind: CdcCrossingKind.fromJsonString(
        json['crossingKind']?.toString() ?? '',
      ),
      synchronizerStatus: CdcSynchronizerStatus.fromJsonString(
        json['synchronizerStatus']?.toString() ?? '',
      ),
      severity: CdcSeverity.fromJsonString(
        json['severity']?.toString() ?? '',
      ),
      confidence: CdcConfidence.fromJsonString(
        json['confidence']?.toString() ?? '',
      ),
      synchronizerInstances: instances is List
          ? <ElementId>[
              for (final i in instances)
                if (i is Map<String, Object?>) ElementId.fromJson(i),
            ]
          : const <ElementId>[],
    );
  }

  /// Stable identifier (UUID-shaped string) generated by the detector.
  final String id;

  /// `ClockDomain.id` of the domain driving this crossing's signal.
  final String sourceDomainId;

  /// `ClockDomain.id` of the domain consuming this crossing's signal.
  final String destinationDomainId;

  /// Cross-suite identifier for the net that crosses domains. The
  /// schematic overlay highlights this net during selection.
  final ElementId signalId;

  /// Human-readable name of the crossing signal (for panel display).
  final String signalName;

  /// What kind of signal is crossing — single-bit control, multi-bit
  /// bus, handshake, etc.
  final CdcCrossingKind crossingKind;

  /// How the crossing is synchronized — proper 2-flop, missing, async
  /// FIFO, etc.
  final CdcSynchronizerStatus synchronizerStatus;

  /// Severity derived from `(crossingKind × synchronizerStatus)`. See
  /// [severityFor] for the full matrix.
  final CdcSeverity severity;

  /// Detector's confidence in this classification.
  final CdcConfidence confidence;

  /// Cross-suite identifiers of the instances forming the synchronizer
  /// chain (or the partner half of a handshake), in source-to-
  /// destination order. The synchronizer-chain detail sub-panel renders
  /// these as a sequence of register icons.
  final List<ElementId> synchronizerInstances;

  /// Deterministic severity derivation from the
  /// `(crossingKind × synchronizerStatus)` matrix.
  ///
  /// **Matrix** (rows = crossingKind, columns = synchronizerStatus):
  ///
  /// ```text
  ///                  | 2ff | 3ff | aFIFO | hsk | cust | missing | meta |
  /// singleBit        | inf | inf | inf   | inf | inf  | crit    | warn |
  /// multiBit         | crit| crit| inf   | warn| inf  | crit    | crit |
  /// control          | inf | inf | inf   | inf | inf  | crit    | warn |
  /// handshake        | inf | inf | inf   | inf | inf  | crit    | warn |
  /// ```
  ///
  /// Rationale:
  ///   * Multi-bit buses through 2-flop sync per bit are *critical* —
  ///     bits desync and produce corrupt values; the only safe
  ///     multi-bit paths are async-FIFO or custom (user-asserted).
  ///   * Missing synchronizer is *critical* for every crossing kind —
  ///     metastability can propagate anywhere.
  ///   * `metastable` status flags real risk on multi-bit (critical —
  ///     bits desync and corrupted samples reach combinational fanout)
  ///     but only a warning on the other kinds (one bit, one consumer).
  ///   * Handshake multi-bit through `handshakeProtocol` is warning
  ///     because the protocol carries control data but the bus
  ///     payload still requires async-FIFO for safety.
  static CdcSeverity severityFor(
    CdcCrossingKind kind,
    CdcSynchronizerStatus status,
  ) {
    switch (status) {
      case CdcSynchronizerStatus.missingSynchronizer:
        return CdcSeverity.critical;
      case CdcSynchronizerStatus.metastable:
        return kind == CdcCrossingKind.multiBit
            ? CdcSeverity.critical
            : CdcSeverity.warning;
      case CdcSynchronizerStatus.properTwoFlopSync:
      case CdcSynchronizerStatus.properThreeFlopSync:
        return kind == CdcCrossingKind.multiBit
            ? CdcSeverity.critical
            : CdcSeverity.info;
      case CdcSynchronizerStatus.handshakeProtocol:
        return kind == CdcCrossingKind.multiBit
            ? CdcSeverity.warning
            : CdcSeverity.info;
      case CdcSynchronizerStatus.asyncFifo:
      case CdcSynchronizerStatus.customSynchronizer:
        return CdcSeverity.info;
    }
  }

  /// Returns a copy with the given fields replaced.
  CdcCrossing copyWith({
    String? id,
    String? sourceDomainId,
    String? destinationDomainId,
    ElementId? signalId,
    String? signalName,
    CdcCrossingKind? crossingKind,
    CdcSynchronizerStatus? synchronizerStatus,
    CdcSeverity? severity,
    CdcConfidence? confidence,
    List<ElementId>? synchronizerInstances,
  }) => CdcCrossing(
    id: id ?? this.id,
    sourceDomainId: sourceDomainId ?? this.sourceDomainId,
    destinationDomainId: destinationDomainId ?? this.destinationDomainId,
    signalId: signalId ?? this.signalId,
    signalName: signalName ?? this.signalName,
    crossingKind: crossingKind ?? this.crossingKind,
    synchronizerStatus: synchronizerStatus ?? this.synchronizerStatus,
    severity: severity ?? this.severity,
    confidence: confidence ?? this.confidence,
    synchronizerInstances: synchronizerInstances ?? this.synchronizerInstances,
  );

  /// JSON map suitable for fixture round-trip.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'sourceDomainId': sourceDomainId,
    'destinationDomainId': destinationDomainId,
    'signalId': signalId.toJson(),
    'signalName': signalName,
    'crossingKind': crossingKind.toJsonString(),
    'synchronizerStatus': synchronizerStatus.toJsonString(),
    'severity': severity.toJsonString(),
    'confidence': confidence.toJsonString(),
    'synchronizerInstances': <Map<String, Object?>>[
      for (final i in synchronizerInstances) i.toJson(),
    ],
  };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! CdcCrossing) return false;
    if (id != other.id) return false;
    if (sourceDomainId != other.sourceDomainId) return false;
    if (destinationDomainId != other.destinationDomainId) return false;
    if (signalId != other.signalId) return false;
    if (signalName != other.signalName) return false;
    if (crossingKind != other.crossingKind) return false;
    if (synchronizerStatus != other.synchronizerStatus) return false;
    if (severity != other.severity) return false;
    if (confidence != other.confidence) return false;
    if (synchronizerInstances.length != other.synchronizerInstances.length) {
      return false;
    }
    for (var i = 0; i < synchronizerInstances.length; i++) {
      if (synchronizerInstances[i] != other.synchronizerInstances[i]) {
        return false;
      }
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    id,
    sourceDomainId,
    destinationDomainId,
    signalId,
    signalName,
    crossingKind,
    synchronizerStatus,
    severity,
    confidence,
    Object.hashAll(synchronizerInstances),
  );

  @override
  String toString() =>
      'CdcCrossing(id: $id, $signalName, '
      '$sourceDomainId→$destinationDomainId, '
      'kind: ${crossingKind.name}, status: ${synchronizerStatus.name}, '
      'severity: ${severity.name}, confidence: ${confidence.name})';
}
