// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:crux_cxp/crux_cxp.dart';
import 'package:meta/meta.dart';
import 'package:netcrux/domain/models/cdc/clock_domain_source_kind.dart';

/// A clock domain detected in the netlist.
///
/// A clock domain is the equivalence class of registers sharing the same
/// effective clock — `clk_50`, the output of a PLL block, the output of
/// an enable-gated AND, etc. Domain identity is keyed by the *driver
/// net* of the clock signal, not by name, so two registers wired to the
/// same net belong to the same domain even when their HDL refers to
/// the net by different aliases.
@immutable
class ClockDomain {
  /// Creates a clock domain record.
  const ClockDomain({
    required this.id,
    required this.clockSignalId,
    required this.clockSignalName,
    required this.sourceKind,
    required this.memberNets,
    required this.memberRegisters,
    this.frequencyHint,
  });

  /// JSON round-trip constructor.
  factory ClockDomain.fromJson(Map<String, Object?> json) {
    final clockRaw = json['clockSignalId'];
    final nets = json['memberNets'];
    final regs = json['memberRegisters'];
    return ClockDomain(
      id: json['id']?.toString() ?? '',
      clockSignalId: clockRaw is Map<String, Object?>
          ? ElementId.fromJson(clockRaw)
          : const ElementId(kind: ElementKind.signal, path: ''),
      clockSignalName: json['clockSignalName']?.toString() ?? '',
      sourceKind: ClockDomainSourceKind.fromJsonString(
        json['sourceKind']?.toString() ?? '',
      ),
      memberNets: nets is List
          ? <ElementId>[
              for (final n in nets)
                if (n is Map<String, Object?>) ElementId.fromJson(n),
            ]
          : const <ElementId>[],
      memberRegisters: regs is List
          ? <ElementId>[
              for (final r in regs)
                if (r is Map<String, Object?>) ElementId.fromJson(r),
            ]
          : const <ElementId>[],
      frequencyHint: json['frequencyHint']?.toString(),
    );
  }

  /// Stable identifier (UUID-shaped string) generated by the detector.
  /// Keys the domain in the analysis result; survives re-analysis when
  /// the underlying clock net is unchanged so panels keep their
  /// selection.
  final String id;

  /// Canonical cross-suite identifier for the net that defines this
  /// clock domain. Always present even when the clock arrives through
  /// glue logic — the detector chooses the final net feeding register
  /// `.clk` ports as the domain's identity.
  final ElementId clockSignalId;

  /// Human-readable name of the clock signal (e.g. `"clk_100mhz"`,
  /// `"pll_out_0"`). Used by panel headers and graph-canvas labels.
  final String clockSignalName;

  /// Best-effort frequency descriptor — `"100MHz"`, `"free-running"`,
  /// `"gated"`, or `null` when the detector could not infer one. Parsed
  /// from clock-signal-name conventions or PLL output parameters; never
  /// asserted as authoritative.
  final String? frequencyHint;

  /// How this clock was sourced. See [ClockDomainSourceKind].
  final ClockDomainSourceKind sourceKind;

  /// Cross-suite identifiers of nets whose driver is a register clocked
  /// by this domain. The CDC analyzer uses this set to determine
  /// "domain of origin" for every net in the design.
  final List<ElementId> memberNets;

  /// Cross-suite identifiers of register cells clocked by this domain.
  /// Their `.q` outputs drive the [memberNets].
  final List<ElementId> memberRegisters;

  /// Returns a copy with the given fields replaced.
  ClockDomain copyWith({
    String? id,
    ElementId? clockSignalId,
    String? clockSignalName,
    String? frequencyHint,
    ClockDomainSourceKind? sourceKind,
    List<ElementId>? memberNets,
    List<ElementId>? memberRegisters,
    bool clearFrequencyHint = false,
  }) => ClockDomain(
    id: id ?? this.id,
    clockSignalId: clockSignalId ?? this.clockSignalId,
    clockSignalName: clockSignalName ?? this.clockSignalName,
    frequencyHint: clearFrequencyHint
        ? null
        : (frequencyHint ?? this.frequencyHint),
    sourceKind: sourceKind ?? this.sourceKind,
    memberNets: memberNets ?? this.memberNets,
    memberRegisters: memberRegisters ?? this.memberRegisters,
  );

  /// JSON map suitable for fixture round-trip.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'clockSignalId': clockSignalId.toJson(),
    'clockSignalName': clockSignalName,
    'sourceKind': sourceKind.toJsonString(),
    'memberNets': <Map<String, Object?>>[
      for (final n in memberNets) n.toJson(),
    ],
    'memberRegisters': <Map<String, Object?>>[
      for (final r in memberRegisters) r.toJson(),
    ],
    if (frequencyHint != null) 'frequencyHint': frequencyHint,
  };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! ClockDomain) return false;
    if (id != other.id) return false;
    if (clockSignalId != other.clockSignalId) return false;
    if (clockSignalName != other.clockSignalName) return false;
    if (frequencyHint != other.frequencyHint) return false;
    if (sourceKind != other.sourceKind) return false;
    if (memberNets.length != other.memberNets.length) return false;
    for (var i = 0; i < memberNets.length; i++) {
      if (memberNets[i] != other.memberNets[i]) return false;
    }
    if (memberRegisters.length != other.memberRegisters.length) return false;
    for (var i = 0; i < memberRegisters.length; i++) {
      if (memberRegisters[i] != other.memberRegisters[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    id,
    clockSignalId,
    clockSignalName,
    frequencyHint,
    sourceKind,
    Object.hashAll(memberNets),
    Object.hashAll(memberRegisters),
  );

  @override
  String toString() =>
      'ClockDomain(id: $id, name: $clockSignalName, '
      'sourceKind: ${sourceKind.name}, '
      '${memberRegisters.length} regs, ${memberNets.length} nets)';
}
