// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:meta/meta.dart';
import 'package:netcrux/domain/models/annotation_target.dart';

/// A note pinned to a schematic element: an optional one-line [title] and
/// an optional Markdown [body], at least one of them non-empty.
///
/// Pure data: no Flutter imports, no callbacks. The body is opaque
/// Markdown — the model does not parse it; the Annotations panel renders
/// it at display time.
@immutable
class Annotation {
  /// Creates an annotation.
  const Annotation({
    required this.id,
    required this.targetKind,
    required this.targetId,
    required this.body,
    required this.createdAtMillis,
    required this.updatedAtMillis,
    this.title,
    this.author,
    this.moduleName,
    this.authorId,
    this.colorArgb,
    this.sessionLayerId,
    this.sessionLayerLabel,
    this.hidden = false,
  });

  /// Reads an annotation back from its JSON shape produced by
  /// [toJson]. Returns `null` when the JSON is malformed, carries an
  /// unknown `targetKind`. A missing `body` reads as empty.
  static Annotation? fromJson(Map<String, Object?> json) {
    final id = json['id'];
    final targetId = json['targetId'];
    final rawBody = json['body'];
    final rawTitle = json['title'];
    final created = json['createdAtMillis'];
    final updated = json['updatedAtMillis'];
    if (id is! String || id.isEmpty) return null;
    if (targetId is! String || targetId.isEmpty) return null;
    if (rawBody != null && rawBody is! String) return null;
    if (created is! int) return null;
    if (updated is! int) return null;
    final kind = annotationTargetKindFromName(json['targetKind']);
    if (kind == null) return null;
    final body = rawBody is String ? rawBody : '';
    final title = normalizeAnnotationTitle(
      rawTitle is String ? rawTitle : null,
    );
    final author = json['author'];
    final moduleName = json['moduleName'];
    final authorId = json['authorId'];
    final colorArgb = json['colorArgb'];
    final layerId = json['sessionLayerId'];
    final layerLabel = json['sessionLayerLabel'];
    return Annotation(
      id: id,
      targetKind: kind,
      targetId: targetId,
      body: body,
      createdAtMillis: created,
      updatedAtMillis: updated,
      title: title,
      author: author is String ? author : null,
      moduleName: moduleName is String && moduleName.isNotEmpty
          ? moduleName
          : null,
      authorId: authorId is String && authorId.isNotEmpty ? authorId : null,
      colorArgb: colorArgb is int ? colorArgb : null,
      sessionLayerId: layerId is String && layerId.isNotEmpty ? layerId : null,
      sessionLayerLabel: layerLabel is String ? layerLabel : null,
      hidden: json['hidden'] == true,
    );
  }

  /// Reads one entry of the `bookmarks` array that older session files
  /// carry, as the annotation it now is: the entry's `name` becomes the
  /// [title], its `note` the [body], and its target, id, creation time,
  /// module and author carry over. Returns `null` for an entry
  /// [fromJson] would reject for the same reasons.
  ///
  /// Read-only: nothing writes this shape.
  static Annotation? fromLegacyBookmarkJson(Map<String, Object?> json) {
    final id = json['id'];
    final targetId = json['targetId'];
    final created = json['createdAtMillis'];
    if (id is! String || id.isEmpty) return null;
    if (targetId is! String || targetId.isEmpty) return null;
    if (created is! int) return null;
    final kind = annotationTargetKindFromName(json['targetKind']);
    if (kind == null) return null;
    final name = json['name'];
    final note = json['note'];
    final title = normalizeAnnotationTitle(name is String ? name : null);
    final body = note is String ? note.trim() : '';
    final author = json['author'];
    final moduleName = json['moduleName'];
    return Annotation(
      id: id,
      targetKind: kind,
      targetId: targetId,
      body: body,
      createdAtMillis: created,
      updatedAtMillis: created,
      title: title,
      author: author is String && author.isNotEmpty ? author : null,
      moduleName: moduleName is String && moduleName.isNotEmpty
          ? moduleName
          : null,
    );
  }

  /// Stable opaque id. Generated by the Pro overlay at creation;
  /// preserved across `.netcrux` round-trips.
  final String id;

  /// Discriminator for [targetId] interpretation.
  final AnnotationTargetKind targetKind;

  /// Element id matching the schematic graph: cell instance name,
  /// `<cellName>:<portName>`, `port:<name>`, edge id, or
  /// `dot.joined.scope.path`.
  final String targetId;

  /// Optional one-line title, shown as the annotation's row in the
  /// Annotations panel. `null` when untitled; never empty.
  final String? title;

  /// Annotation body. Markdown source, possibly empty when the annotation
  /// has a [title]. The model does not parse it; the panel renders it.
  final String body;

  /// Optional free-text author label (e.g. `'a.engineer'`,
  /// `'design-review'`). `null` = unattributed.
  final String? author;

  /// Creation timestamp (milliseconds since epoch).
  final int createdAtMillis;

  /// Last-edit timestamp (milliseconds since epoch). Equals
  /// [createdAtMillis] until the first edit. Surfaces in the panel
  /// so reviewers can see when a note was updated.
  final int updatedAtMillis;

  /// The module of the scope the target was annotated in, or `null` for an
  /// annotation written before the field existed, or one whose target is a
  /// scope. Cell, pin, port and net ids are local to a module: it says
  /// which module's `u_fifo` the note is on, so revealing it navigates to a
  /// scope of that module and the schematic badges the element only in
  /// scopes of that module.
  final String? moduleName;

  /// The collaborative-session participant who wrote this note, while the
  /// note belongs to somebody else. `null` for a note of your own.
  ///
  /// It is what makes attribution read-only: a note that carries another
  /// participant's id may be hidden or deleted, but not edited while their
  /// name stays on it. A session clears it on the notes you wrote when you
  /// keep them, so your own notes are yours to edit again.
  final String? authorId;

  /// The author's colour as an ARGB value, frozen when the note was written in
  /// a session. Stored as a colour rather than a palette slot: slots are
  /// reassigned every session, and a slot would recolour and misattribute last
  /// week's notes the next time the room met. `null` for a note written
  /// outside a session, which takes the theme's colour.
  final int? colorArgb;

  /// The session layer this note belongs to, or `null` for a note written
  /// outside a session. A layer groups one meeting's notes so they can be
  /// hidden or deleted as a unit.
  final String? sessionLayerId;

  /// The layer's human label (which session, and when), or `null`.
  final String? sessionLayerLabel;

  /// Whether the note is hidden from the canvas — set and cleared a layer at
  /// a time.
  final bool hidden;

  /// Returns a copy with selected fields replaced. [updatedAtMillis]
  /// must be supplied explicitly — `copyWith` does *not* auto-bump it
  /// because the caller (the store) knows when the change happened.
  Annotation copyWith({
    String? id,
    AnnotationTargetKind? targetKind,
    String? targetId,
    String? body,
    String? title,
    bool clearTitle = false,
    String? author,
    int? createdAtMillis,
    int? updatedAtMillis,
    String? moduleName,
    String? authorId,
    bool clearAuthorId = false,
    int? colorArgb,
    String? sessionLayerId,
    String? sessionLayerLabel,
    bool? hidden,
  }) {
    return Annotation(
      id: id ?? this.id,
      targetKind: targetKind ?? this.targetKind,
      targetId: targetId ?? this.targetId,
      body: body ?? this.body,
      title: clearTitle ? null : (title ?? this.title),
      author: author ?? this.author,
      createdAtMillis: createdAtMillis ?? this.createdAtMillis,
      updatedAtMillis: updatedAtMillis ?? this.updatedAtMillis,
      moduleName: moduleName ?? this.moduleName,
      authorId: clearAuthorId ? null : (authorId ?? this.authorId),
      colorArgb: colorArgb ?? this.colorArgb,
      sessionLayerId: sessionLayerId ?? this.sessionLayerId,
      sessionLayerLabel: sessionLayerLabel ?? this.sessionLayerLabel,
      hidden: hidden ?? this.hidden,
    );
  }

  /// Round-trip JSON. Forward-compatible.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'targetKind': targetKind.name,
    'targetId': targetId,
    if (title != null) 'title': title,
    'body': body,
    'createdAtMillis': createdAtMillis,
    'updatedAtMillis': updatedAtMillis,
    if (author != null) 'author': author,
    if (moduleName != null) 'moduleName': moduleName,
    if (authorId != null) 'authorId': authorId,
    if (colorArgb != null) 'colorArgb': colorArgb,
    if (sessionLayerId != null) 'sessionLayerId': sessionLayerId,
    if (sessionLayerLabel != null) 'sessionLayerLabel': sessionLayerLabel,
    if (hidden) 'hidden': true,
  };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Annotation) return false;
    return other.id == id &&
        other.targetKind == targetKind &&
        other.targetId == targetId &&
        other.title == title &&
        other.body == body &&
        other.author == author &&
        other.createdAtMillis == createdAtMillis &&
        other.updatedAtMillis == updatedAtMillis &&
        other.moduleName == moduleName &&
        other.authorId == authorId &&
        other.colorArgb == colorArgb &&
        other.sessionLayerId == sessionLayerId &&
        other.sessionLayerLabel == sessionLayerLabel &&
        other.hidden == hidden;
  }

  @override
  int get hashCode => Object.hash(
    id,
    targetKind,
    targetId,
    title,
    body,
    author,
    createdAtMillis,
    updatedAtMillis,
    moduleName,
    authorId,
    colorArgb,
    sessionLayerId,
    sessionLayerLabel,
    hidden,
  );

  /// The line the Annotations panel shows for this annotation: the
  /// [title], or the first non-blank line of the [body] when untitled.
  String get heading {
    final t = title;
    if (t != null) return t;
    for (final line in body.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.isNotEmpty) return trimmed;
    }
    return '';
  }

  @override
  String toString() =>
      'Annotation($id, $targetKind:$targetId, ${body.length}b)';
}

/// An annotation title as stored: trimmed, folded onto one line, and
/// `null` when nothing is left.
String? normalizeAnnotationTitle(String? raw) {
  if (raw == null) return null;
  final folded = raw.replaceAll(RegExp(r'\s+'), ' ').trim();
  return folded.isEmpty ? null : folded;
}
