// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:meta/meta.dart';
import 'package:netcrux/domain/models/bookmark.dart';

/// A free-text note (markdown body) pinned to a schematic element.
///
/// Distinct from [Bookmark]: bookmarks are short navigation pointers
/// (a name + an optional color + an optional note); annotations carry
/// the prose explaining *why* a particular element matters. Both
/// share the same [BookmarkTargetKind] target taxonomy so the UI can
/// render them in a single per-element overlay if it wants to.
///
/// Pure data: no Flutter imports, no callbacks. Body is opaque
/// markdown — the open-core model does not parse it; the Pro panel
/// renders it (with `flutter_markdown_plus` if available, plain text
/// otherwise) at display time.
@immutable
class Annotation {
  /// Creates an annotation.
  const Annotation({
    required this.id,
    required this.targetKind,
    required this.targetId,
    required this.body,
    required this.createdAtMillis,
    required this.updatedAtMillis,
    this.author,
  });

  /// Reads an annotation back from its JSON shape produced by
  /// [toJson]. Returns `null` when the JSON is malformed or carries
  /// an unknown `targetKind`.
  static Annotation? fromJson(Map<String, Object?> json) {
    final id = json['id'];
    final kindStr = json['targetKind'];
    final targetId = json['targetId'];
    final body = json['body'];
    final created = json['createdAtMillis'];
    final updated = json['updatedAtMillis'];
    if (id is! String || id.isEmpty) return null;
    if (kindStr is! String) return null;
    if (targetId is! String || targetId.isEmpty) return null;
    if (body is! String) return null;
    if (created is! int) return null;
    if (updated is! int) return null;
    final kind = BookmarkTargetKind.values
        .where((k) => k.name == kindStr)
        .cast<BookmarkTargetKind?>()
        .firstWhere((k) => k != null, orElse: () => null);
    if (kind == null) return null;
    final author = json['author'];
    return Annotation(
      id: id,
      targetKind: kind,
      targetId: targetId,
      body: body,
      createdAtMillis: created,
      updatedAtMillis: updated,
      author: author is String ? author : null,
    );
  }

  /// Stable opaque id. Generated by the Pro overlay at creation;
  /// preserved across `.netcrux` round-trips.
  final String id;

  /// Discriminator for [targetId] interpretation. Shares
  /// [Bookmark]'s taxonomy.
  final BookmarkTargetKind targetKind;

  /// Element id matching the schematic graph — same shape as
  /// [Bookmark.targetId].
  final String targetId;

  /// Annotation body. Markdown source. The open-core model does not
  /// parse it; the Pro panel handles rendering.
  final String body;

  /// Optional free-text author label (e.g. `'a.engineer'`,
  /// `'design-review'`). `null` = unattributed.
  final String? author;

  /// Creation timestamp (milliseconds since epoch).
  final int createdAtMillis;

  /// Last-edit timestamp (milliseconds since epoch). Equals
  /// [createdAtMillis] until the first edit. Surfaces in the panel
  /// so reviewers can see when a note was updated.
  final int updatedAtMillis;

  /// Returns a copy with selected fields replaced. [updatedAtMillis]
  /// must be supplied explicitly — `copyWith` does *not* auto-bump it
  /// because the caller (the store) knows when the change happened.
  Annotation copyWith({
    String? id,
    BookmarkTargetKind? targetKind,
    String? targetId,
    String? body,
    String? author,
    int? createdAtMillis,
    int? updatedAtMillis,
  }) {
    return Annotation(
      id: id ?? this.id,
      targetKind: targetKind ?? this.targetKind,
      targetId: targetId ?? this.targetId,
      body: body ?? this.body,
      author: author ?? this.author,
      createdAtMillis: createdAtMillis ?? this.createdAtMillis,
      updatedAtMillis: updatedAtMillis ?? this.updatedAtMillis,
    );
  }

  /// Round-trip JSON. Forward-compatible.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'targetKind': targetKind.name,
    'targetId': targetId,
    'body': body,
    'createdAtMillis': createdAtMillis,
    'updatedAtMillis': updatedAtMillis,
    if (author != null) 'author': author,
  };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Annotation) return false;
    return other.id == id &&
        other.targetKind == targetKind &&
        other.targetId == targetId &&
        other.body == body &&
        other.author == author &&
        other.createdAtMillis == createdAtMillis &&
        other.updatedAtMillis == updatedAtMillis;
  }

  @override
  int get hashCode => Object.hash(
    id,
    targetKind,
    targetId,
    body,
    author,
    createdAtMillis,
    updatedAtMillis,
  );

  @override
  String toString() =>
      'Annotation($id, $targetKind:$targetId, ${body.length}b)';
}
