// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:meta/meta.dart';

/// The kind of schematic element a [Bookmark] / [Annotation] targets.
///
/// Kept narrow on purpose: only schematic-visible elements get a stable
/// targetId in the persisted bookmark/annotation. Generate-block
/// expansions or hierarchy nodes that change across re-elaboration
/// would be unstable bookmark targets, so they are deliberately
/// excluded from the v1 enum. Future kinds (transaction, instruction
/// trace) belong to other tools' bookmarks anyway.
enum BookmarkTargetKind {
  /// A schematic cell (a Yosys cell instance — e.g. `u_alu`).
  cell,

  /// A pin on a cell (e.g. `u_alu:A`).
  port,

  /// A boundary port on the active scope (e.g. `port:reset_n`).
  boundaryPort,

  /// A wire / net (e.g. the edge id `e_4` referencing Yosys net 4).
  net,

  /// A hierarchical scope navigated to by name path (e.g.
  /// `top.cpu.alu`). Bookmarks of this kind do not pin a specific
  /// element inside the scope — they remember the *scope* the user
  /// wanted to come back to.
  scope,
}

/// A persistent named pointer to a schematic element.
///
/// Bookmarks are part of the [`NetcruxSession`] model and round-trip
/// through `.netcrux` session JSON. They are the open-core data shape;
/// the Pro overlay's [`BookmarkAnnotationStore`] implementation
/// persists them into the active session, and the Pro UI surface
/// renders them in a bookmarks panel.
///
/// Pure data: no Flutter imports, no callbacks. The `id` is generated
/// by the Pro overlay at creation time (millis-since-epoch + counter
/// for v1; can move to a real UUID later without breaking compatibility
/// because the field is an opaque string).
@immutable
class Bookmark {
  /// Creates a bookmark.
  const Bookmark({
    required this.id,
    required this.name,
    required this.targetKind,
    required this.targetId,
    required this.createdAtMillis,
    this.colorHex,
    this.note,
  });

  /// Reads a bookmark back from its JSON shape produced by [toJson].
  /// Returns `null` when the JSON is malformed or carries an unknown
  /// `targetKind` — bookmarks tolerate forward-incompatible additions
  /// without breaking session load.
  static Bookmark? fromJson(Map<String, Object?> json) {
    final id = json['id'];
    final name = json['name'];
    final kindStr = json['targetKind'];
    final targetId = json['targetId'];
    final created = json['createdAtMillis'];
    if (id is! String || id.isEmpty) return null;
    if (name is! String) return null;
    if (kindStr is! String) return null;
    if (targetId is! String || targetId.isEmpty) return null;
    if (created is! int) return null;
    final kind = BookmarkTargetKind.values
        .where((k) => k.name == kindStr)
        .cast<BookmarkTargetKind?>()
        .firstWhere((k) => k != null, orElse: () => null);
    if (kind == null) return null;
    final color = json['colorHex'];
    final note = json['note'];
    return Bookmark(
      id: id,
      name: name,
      targetKind: kind,
      targetId: targetId,
      createdAtMillis: created,
      colorHex: color is String ? color : null,
      note: note is String ? note : null,
    );
  }

  /// Stable opaque id. Generated by the Pro overlay at creation;
  /// preserved across `.netcrux` round-trips.
  final String id;

  /// User-visible label.
  final String name;

  /// Discriminator for [targetId] interpretation.
  final BookmarkTargetKind targetKind;

  /// Element id matching the schematic graph: cell instance name,
  /// `<cellName>:<portName>`, `port:<name>`, edge id, or
  /// `dot.joined.scope.path`.
  final String targetId;

  /// Creation timestamp (milliseconds since epoch). Used for sort
  /// order in the panel and as a tie-breaker for id generation.
  final int createdAtMillis;

  /// Optional swatch color stored as `#RRGGBB` or `#AARRGGBB` hex.
  /// `null` = default color from the active theme.
  final String? colorHex;

  /// Optional free-text note attached to the bookmark.
  final String? note;

  /// Returns a copy with selected fields replaced.
  Bookmark copyWith({
    String? id,
    String? name,
    BookmarkTargetKind? targetKind,
    String? targetId,
    int? createdAtMillis,
    String? colorHex,
    String? note,
  }) {
    return Bookmark(
      id: id ?? this.id,
      name: name ?? this.name,
      targetKind: targetKind ?? this.targetKind,
      targetId: targetId ?? this.targetId,
      createdAtMillis: createdAtMillis ?? this.createdAtMillis,
      colorHex: colorHex ?? this.colorHex,
      note: note ?? this.note,
    );
  }

  /// Round-trip JSON. Forward-compatible: unknown keys on the way back
  /// in are silently dropped.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'name': name,
    'targetKind': targetKind.name,
    'targetId': targetId,
    'createdAtMillis': createdAtMillis,
    if (colorHex != null) 'colorHex': colorHex,
    if (note != null) 'note': note,
  };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Bookmark) return false;
    return other.id == id &&
        other.name == name &&
        other.targetKind == targetKind &&
        other.targetId == targetId &&
        other.createdAtMillis == createdAtMillis &&
        other.colorHex == colorHex &&
        other.note == note;
  }

  @override
  int get hashCode => Object.hash(
    id,
    name,
    targetKind,
    targetId,
    createdAtMillis,
    colorHex,
    note,
  );

  @override
  String toString() => 'Bookmark($id, $targetKind:$targetId, name="$name")';
}
